jobs:
  - job: reportReleaseStarted
    displayName: 'report: Release Started'
    steps:
    - task: PowerShell@2
      name: 'report_release_started'
      env:
          SLACK_TOKEN: $(SLACK_TOKEN)
          CHANNEL_ID: $(CHANNEL_ID)
      displayName: 'Report: Release Started'
      continueOnError: true
      inputs:
        filePath: $(System.DefaultWorkingDirectory)/infrastructure/DeploymentSlackReporting.ps1
        arguments: -action Started -Verbose
        errorActionPreference: 'continue'
